# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost/fueling
    username: root
    password: Alicante15!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh


#logging:
#  level:
#    org.springframework:
#      security: DEBUG